version: '2.0'

services:
  #  ca:
  #    image: hyperledger/fabric-ca
  #    container_name: ca0
  #    ports:
  #      - "7054:7054"
  #    environment:
  #      - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca-server
  #    volumes:
  #      - "./ca:/etc/hyperledger/fabric-ca-server"
  #    command: sh -c 'fabric-ca-server start -b admin:adminpw'

  orderer0:  # There  can be multiple orderers
    image: hyperledger/fabric-orderer
    container_name: orderer0
    hostname: orderer0
    environment:
        - ORDERER_GENERAL_LOGLEVEL=debug
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
        - ORDERER_GENERAL_LOCALMSPID=OrdererOrgMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/solo/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./cas/mspconfig/OrdererOrg/msp:/var/hyperledger/orderer/msp
    ports:
      - "7050:7050"

  couchdb1.1:
    image: hyperledger/fabric-couchdb
    container_name: couchdb1.1
    hostname: couchdb1.1
    ports:
      - "5984:5984"

  peer1.1:
    image: hyperledger/fabric-peer
    container_name: peer1.1
    hostname: peer1.1
    environment:
      - CORE_PEER_ID=peer1.1
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.1:5984
      - GOPATH=/opt/gopath
    expose:
      - "7050"  # Rest
      - "7051"  # Grpc
      - "7052"  # Peer CLI
      - "7053"  # Peer Event
      - "7054"  # eCAP
      - "7055"  # eCAA
      - "7056"  # tCAP
      - "7057"  # eCAA
      - "7058"  # tlsCAP
      - "7059"  # tlsCAA
    links:
      - orderer0
    ports:
      - 7051:7051
    depends_on:
      - orderer0
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cas/mspconfig/Org1/msp/:/etc/hyperledger/fabric/msp

  couchdb2.1:
    image: hyperledger/fabric-couchdb
    container_name: couchdb2.1
    hostname: couchdb2.1
    ports:
      - "6984:5984"

  peer2.1:
    image: hyperledger/fabric-peer
    container_name: peer2.1
    hostname: peer2.1
    environment:
      - CORE_PEER_ID=peer2.1
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2.1:5984
      - GOPATH=/opt/gopath
    expose:
      - "7050"  # Rest
      - "7051"  # Grpc
      - "7052"  # Peer CLI
      - "7053"  # Peer Event
      - "7054"  # eCAP
      - "7055"  # eCAA
      - "7056"  # tCAP
      - "7057"  # eCAA
      - "7058"  # tlsCAP
      - "7059"  # tlsCAA
    links:
      - orderer0
      - peer1.1
    depends_on:
      - orderer0
      - peer1.1
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cas/mspconfig/Org2/msp:/etc/hyperledger/fabric/msp
    ports:
      - 8051:7051

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      # TLS settings
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_ADDRESS=peer1.1:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/config
    command: /bin/bash -c 'sleep 6000000000000000000'
    volumes:
      - /var/run/:/host/var/run/
      - ./cas/mspconfig/:/var/hyperledger
      - ./channel-artifacts/solo:/opt/gopath/src/github.com/hyperledger/fabric/config
        #- /home/blockchain/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go:/opt/gopath/src/chaincode/go
      - /home/guigui/projects/src/github.com/hyperledger/fabric/examples/chaincode/go:/opt/gopath/src/chaincode/go
    ports:
      - '9092'
    depends_on:
      - orderer0
      - peer1.1
      - peer2.1
