version: '2.0'

services:

  ca:
    image: hyperledger/fabric-ca
    container_name: ca0
    ports:
      - "7054:7054"
    environment:
      - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca-server
    volumes:
      - "./ca:/etc/hyperledger/fabric-ca-server"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'

  orderer0:  # There  can be multiple orderers
    image: hyperledger/fabric-orderer
    container_name: orderer0
    hostname: orderer0
    environment:
        - ORDERER_GENERAL_LOGLEVEL=debug
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
        - ORDERER_GENERAL_LOCALMSPID=BlockChainCoCMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/solo/orderer.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./ca/BlockChainCoCMSP/orderer0/msp:/var/hyperledger/orderer/msp
    ports:
      - "7050:7050"
  
  couchdb0:
    image: hyperledger/fabric-couchdb
    container_name: couchdb0
    hostname: couchdb0
    ports:
      - "5984:5984"

  peer0:
    image: hyperledger/fabric-peer
    container_name: peer0
    hostname: peer0
    environment:
      - CORE_PEER_ID=peer0
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_LOCALMSPID=BlockChainCoCMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - GOPATH=/opt/gopath
    expose:
      - "7050"  # Rest
      - "7051"  # Grpc
      - "7052"  # Peer CLI
      - "7053"  # Peer Event
      - "7054"  # eCAP
      - "7055"  # eCAA
      - "7056"  # tCAP
      - "7057"  # eCAA
      - "7058"  # tlsCAP
      - "7059"  # tlsCAA
    links:
      - orderer0
    ports:
      - 7051:7051
    depends_on:
      - orderer0
      - couchdb0
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ca/BlockChainCoCMSP/peer0/msp/:/etc/hyperledger/fabric/msp

  couchdb1:
    image: hyperledger/fabric-couchdb
    container_name: couchdb1
    hostname: couchdb1
    ports:
      - 6984:5984

  peer1:
    image: hyperledger/fabric-peer
    container_name: peer1
    hostname: peer1
    environment:
      - CORE_PEER_ID=peer1
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_LOCALMSPID=BlockChainCoCMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - GOPATH=/opt/gopath
    expose:
      - "7050"  # Rest
      - "7051"  # Grpc
      - "7052"  # Peer CLI
      - "7053"  # Peer Event
      - "7054"  # eCAP
      - "7055"  # eCAA
      - "7056"  # tCAP
      - "7057"  # eCAA
      - "7058"  # tlsCAP
      - "7059"  # tlsCAA
    links:
      - orderer0
      - peer0
    depends_on:
      - orderer0
      - peer0
      - couchdb1
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ca/BlockChainCoCMSP/peer1/msp:/etc/hyperledger/fabric/msp
    ports:
      - 8051:7051

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      # TLS settings
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_LOCALMSPID=BlockChainCoCMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_ADDRESS=peer0:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/config
    command: /bin/bash -c 'sleep 6000000000000000000'
    volumes:
      - /var/run/:/host/var/run/
      - ./ca/BlockChainCoCMSP/admins/msp/:/var/hyperledger/msp
      - ./channel-artifacts/solo:/opt/gopath/src/github.com/hyperledger/fabric/config
      - /home/blockchain/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02/:/opt/gopath/src/chaincode/go
    ports:
      - '9092'
    depends_on:
      - orderer0
      - peer0
      - peer1
